language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip3 install pyshacl
  - pip install PyLD
  - pip install requests

script:
  - python ./validation/validateActivities.py
  - python ./validation/validateProcotol.py
